#!/usr/bin/env python3
"""Transcribe base-assets.md into src/catalog-spec.js.

The markdown is the master list an artist edits; this makes the JS a
derived file so the two cannot drift. Re-run after editing the markdown.
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / 'base-assets.md'
OUT = ROOT / 'src' / 'catalog-spec.js'

SECTION_OF = {
    'Ground and foundations': 'ground',
    'Roads and circulation': 'road',
    'Perimeter and access': 'perimeter',
    'Defense and observation': 'defense',
    'Command and communications': 'command',
    'Personnel and medical': 'personnel',
    'Logistics and storage': 'logistics',
    'Industry and maintenance': 'industry',
    'Power, life support and utilities': 'utility',
    'Air, orbital and drone operations': 'air',
    'Field devices and deployable protection': 'field',
    'Identity, interiors and environmental props': 'prop',
    'Research': 'research',
}

def ports_for(section, rid):
    if section == 'perimeter':
        return ['wall'] if not rid.startswith('fence') else ['fence']
    if rid.startswith('road_'):
        return ['road']
    if rid.startswith('walk_'):
        return ['walk']
    if rid in ('prop_vent', 'prop_antenna'):
        return ['roof']
    if section in ('command', 'personnel', 'logistics', 'industry', 'utility', 'air', 'defense', 'research'):
        return ['road']
    return ['none']

rows, section = [], None
for line in SRC.read_text(encoding='utf-8').splitlines():
    m = re.match(r'^## (.+)$', line)
    if m:
        section = SECTION_OF.get(m.group(1).strip())
        continue
    m = re.match(r'^\| `([a-z0-9_]+)` \| ([^|]+) \| (\d+) × (\d+) \| ([^|]+) \|$', line)
    if m and section:
        rid, name, px, pz, note = m.groups()
        rows.append((rid, name.strip(), section, int(px), int(pz), ports_for(section, rid), note.strip()))

if len(rows) != 111:
    sys.exit(f'expected 111 rows, parsed {len(rows)}')

def js_str(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"

lines = [
    '// catalog-spec.js — GENERATED by scripts/gen-catalog-spec.py from',
    '// base-assets.md. Do not edit by hand; edit the markdown and re-run.',
    '// Plots are in 4 m cells, X by Z. Pure: no DOM, no three.js.',
    '',
    'export const SECTIONS = ' + str(list(dict.fromkeys(SECTION_OF.values()))).replace('"', "'") + ';',
    '',
    'export const CATALOG_SPEC = [',
]
for rid, name, section, px, pz, ports, note in rows:
    ports_js = '[' + ', '.join(js_str(p) for p in ports) + ']'
    lines.append(f"  {{ id: {js_str(rid)}, name: {js_str(name)}, section: {js_str(section)}, "
                 f"plot: [{px}, {pz}], ports: {ports_js}, note: {js_str(note)} }},")
lines += [
    '];',
    '',
    'const byId = new Map(CATALOG_SPEC.map((r) => [r.id, r]));',
    'export const specById = (id) => byId.get(id);',
    '',
]
OUT.write_text('\n'.join(lines), encoding='utf-8')
print(f'wrote {OUT.relative_to(ROOT)} with {len(rows)} rows')
